#!/bin/bash


while getopts "t:" OPTION
do
  case $OPTION in
      t)
	  TARGET="$OPTARG"
	  ;;
      esac
  done


if [[ -z $TARGET ]]; then
    echo "target (-t) not specified"
    exit 1
fi


if [ -f /tmp/buildfail ]; then
    echo "Build failed on demand"
    exit 1
fi
